///////////////////////////////////////////////////////////
//  Anulada.cs
//  Implementation of the Class Anulada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:16:47
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Anulada : EstadoSM
    {
        public Anulada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsAnulada()
        {
            return true;
        }
        
    }
}