///////////////////////////////////////////////////////////
//  Aplicacion.cs
//  Implementation of the Class Aplicacion
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 20:08:17
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("aplicacion")]
    public class Aplicacion : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Version> Versiones { get; set; }

        public Aplicacion()
        {

        }
    }
}
//end Aplicacion