///////////////////////////////////////////////////////////
//  Cancelada.cs
//  Implementation of the Class Cancelada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:16:54
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Cancelada : EstadoSM
    {

        public Cancelada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsCancelada()
        {
            return true;
        }

    }
}


