///////////////////////////////////////////////////////////
//  Cerrada.cs
//  Implementation of the Class Cerrada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:00
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Cerrada : EstadoSM
    {

        public Cerrada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsCerrada()
        {

            return true;
        }

    }
}
//end Cerrada