///////////////////////////////////////////////////////////
//  Cliente.cs
//  Implementation of the Class Cliente
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:55:24
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace RealizacionCU22.Modelo
{
    [Table("cliente")]
    public class Cliente : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Domicilio { get; set; }
        public DateTime FechaAlta { get; set; }
        public string Nombre { get; set; }
        
        public Cliente(string id, string domicilio, DateTime fechaAlta, string nombre)
        {
            this.Id = int.Parse(id);
            this.Domicilio = domicilio;
            this.FechaAlta = fechaAlta;
            this.Nombre = nombre;
        }
        public Cliente() { }
        public string toString()
        {
            return "Nombre: " + this.Nombre + ". Domicilio: " + this.Domicilio + ". Fecha de Alta: " + this.FechaAlta.ToString("DD/MM/YYYY");
        }
    }
}

//end Cliente