///////////////////////////////////////////////////////////
//  Comentario.cs
//  Implementation of the Class Comentario
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 19:54:32
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{

    [Table("comentario")]
    public class Comentario : IObjetoPersistente
    {

        [Key]
        public int Id { get; set; }
        public string Texto { get; set; }
        public DateTime FechaHora { get; set; }

        public Comentario()
        {

        }

    }
}
//end Comentario

