///////////////////////////////////////////////////////////
//  Confirmada.cs
//  Implementation of the Class Confirmada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:03
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Confirmada : EstadoSM
    {

        public Confirmada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsConfirmada()
        {
            return true;
        }

    }
}



//end Confirmada