///////////////////////////////////////////////////////////
//  EnEjecucion.cs
//  Implementation of the Class EnEjecucion
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:59
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace RealizacionCU22.Modelo
{
    
    public class EnEjecucion : EstadoSM
    {

        public EnEjecucion()
        {
            this.Nombre = this.GetType().ToString();
        }
               
        public new bool EsEnEjecucion()
        {
            return true;
        }

        
        public new void RegistrarResolucion(SolicitudMantenimiento sm)
        {
            var viejo = sm.UltimoHistorial();
            if(viejo != null)
            {
                viejo.FechaHoraHasta = DateTime.Now;
                sm.EstadoActual = new Resuelta();

                HistorialEstadoSM nuevo = new HistorialEstadoSM();
                nuevo.FechaHoraDesde = DateTime.Now;
                nuevo.Estado = new Resuelta();
                sm.HistorialesEstadoSM.Add(nuevo);
            }
            throw new InvalidOperationException("El modelo no es valido");
        }

    }
}


//end EnEjecucion