///////////////////////////////////////////////////////////
//  EnEjecucion.cs
//  Implementation of the Class EnEjecucion
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:59
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace RealizacionCU22.Modelo
{
    
    public class EnEjecucion : EstadoSM
    {

        public EnEjecucion()
        {
            this.Nombre = "En Ejecucion";
        }
               
        public new bool EsEnEjecucion()
        {
            return true;
        }

        
        public override void RegistrarResolucion(SolicitudMantenimiento sm)
        {
            var viejo = sm.UltimoHistorial();
            if (viejo == null)
                viejo = new HistorialEstadoSM();


            viejo.FechaHoraDesde = DateTime.Now;
            viejo.FechaHoraHasta = DateTime.Now;
            viejo.Estado = sm.EstadoActual;

            sm.EstadoActual = new Resuelta();

            HistorialEstadoSM nuevo = new HistorialEstadoSM();
            nuevo.FechaHoraDesde = DateTime.Now;
            nuevo.Estado = new Resuelta();
            sm.HistorialesEstadoSM.Add(nuevo);
            
        }

    }
}


//end EnEjecucion