///////////////////////////////////////////////////////////
//  EstadoTicket.cs
//  Implementation of the Class EstadoTicket
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 18:51:58
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("estado_ticket")]
    public class EstadoTicket : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }

        public EstadoTicket()
        {

        }

        public bool esCerrado()
        {
            return Nombre == "Cerrado";
        }

        public bool esEnEjecucion()
        {
            return Nombre == "En Ejecucion";
        }

        public bool soyEstadoTicket(EstadoTicket estado)
        {
            return this == estado;
        }

    }
}//end EstadoTicket