///////////////////////////////////////////////////////////
//  EstadoSM.cs
//  Implementation of the Class EstadoSM
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:13
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("estado_solicitud_mantenimiento")]
    public class EstadoSM : IObjetoPersistente
    {

        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }

        public EstadoSM()
        {

        }

        public bool EsAnulada()
        {

            return false;
        }

        public bool EsCancelada()
        {

            return false;
        }

        public bool EsCerrada()
        {

            return false;
        }

        public bool EsConfirmada()
        {

            return false;
        }

        public bool EsEnEjecucion()
        {

            return false;
        }

        public bool EsEstimada()
        {

            return false;
        }

        public bool EsGenerada()
        {

            return false;
        }

        public bool EsNotificada()
        {

            return false;
        }

        public bool EsPlanificada()
        {

            return false;
        }

        public bool EsReclamada()
        {

            return false;
        }

        public bool EsResuelta()
        {

            return false;
        }
        public void RegistrarResolucion(SolicitudMantenimiento sm)
        {
            return;
        }

    }
}
//end EstadoSM