///////////////////////////////////////////////////////////
//  EstadoSM.cs
//  Implementation of the Class EstadoSM
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:13
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("estado_solicitud_mantenimiento")]
    public abstract class EstadoSM : IObjetoPersistente
    {

        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }

        public EstadoSM()
        {

        }

        public virtual bool EsAnulada()
        {

            return false;
        }

        public virtual bool EsCancelada()
        {

            return false;
        }

        public virtual bool EsCerrada()
        {

            return false;
        }

        public virtual bool EsConfirmada()
        {

            return false;
        }

        public virtual bool EsEnEjecucion()
        {
            return false;
        }

        public virtual bool EsEstimada()
        {

            return false;
        }

        public virtual bool EsGenerada()
        {

            return false;
        }

        public virtual bool EsNotificada()
        {

            return false;
        }

        public virtual bool EsPlanificada()
        {

            return false;
        }

        public virtual bool EsReclamada()
        {

            return false;
        }

        public virtual bool EsResuelta()
        {

            return false;
        }
        public virtual void RegistrarResolucion(SolicitudMantenimiento sm)
        {

        }

    }
}
//end EstadoSM