///////////////////////////////////////////////////////////
//  Estimada.cs
//  Implementation of the Class Estimada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:18
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Estimada : EstadoSM
    {

        public Estimada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsEstimada()
        {

            return true;
        }

    }
}
//end Estimada