///////////////////////////////////////////////////////////
//  Generada.cs
//  Implementation of the Class Generada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:22
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Generada : EstadoSM
    {

        public Generada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsGenerada()
        {

            return true;
        }

    }
}


//end Generada