///////////////////////////////////////////////////////////
//  HistorialEstadoSM.cs
//  Implementation of the Class HistorialEstadoSM
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:25
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace RealizacionCU22.Modelo
{
    [Table("historial_estado_solicitud")]
    public class HistorialEstadoSM : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public DateTime FechaHoraDesde { get; set; }
        public DateTime? FechaHoraHasta { get; set; }
        public virtual EstadoSM Estado { get; set; }

        /// 
        /// <param name="fecha"></param>
        /// <param name="estado"></param>
        public HistorialEstadoSM(DateTime fecha, EstadoSM estado)
        {
            this.Estado = estado;
            this.FechaHoraDesde = fecha;
        }
        public HistorialEstadoSM()
        {

        }
        public bool EsCerrado()
        {
            return Estado.EsCerrada() && FechaHoraHasta != null;
        }

        public bool EsPrimeroEnEjecucion()
        {
            return EsVigente() && Estado.EsEnEjecucion();
        }

        public bool EsVigente()
        {
            return FechaHoraHasta.HasValue;
        }
    }
}


//end HistorialEstadoSM