///////////////////////////////////////////////////////////
//  LiderProyecto.cs
//  Implementation of the Class LiderProyecto
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 19:55:01
//  Original author: chgag
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("lider_proyecto")]
    public class LiderProyecto : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Apellido { get; set; }
        public string CorreoElectrónico { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Proyecto> ProyectosQueLidera { get; set; }
        public virtual Usuario Usuario { get; set; }

        public LiderProyecto()
        {

        }

        ~LiderProyecto()
        {

        }

        public virtual void Dispose()
        {

        }

        public void conocerProyectosQueLidera()
        {

        }

        public void conocerUsuario()
        {

        }

        public void crear()
        {

        }

        public void mostrarApellido()
        {

        }

        public void mostrarCorreoElectrónico()
        {

        }

        public void mostrarLiderProyecto()
        {

        }

        public void mostrarMisProyectos()
        {

        }

        public void mostrarNombre()
        {

        }

        public void mostrarSolicitudesDeProyectos()
        {

        }

    }
}
//end LiderProyecto