///////////////////////////////////////////////////////////
//  MiembroEquipo.cs
//  Implementation of the Class MiembroEquipo
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 19:55:05
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("miembro_equipo")]
    public class MiembroEquipo : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Apellido { get; set; }
        public string CorreoElectronico { get; set; }
        public string Nombre { get; set; }
        public Usuario Usuario { get; set; }
        public Rol Rol { get; set; }


        public MiembroEquipo()
        {

        }

        ~MiembroEquipo()
        {

        }

        public virtual void Dispose()
        {

        }

        public void conocerRol()
        {

        }

        public void conocerUsuario()
        {

        }

        public void crear()
        {

        }

        public void esMiRol()
        {

        }

        public void mostrarApellido()
        {

        }

        public void mostrarMiembroEquipo()
        {

        }

        public void mostrarNombre()
        {

        }

        public void mostrarNombreRol()
        {

        }

    }
}
//end MiembroEquipo