///////////////////////////////////////////////////////////
//  Notificada.cs
//  Implementation of the Class Notificada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:29
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Notificada : EstadoSM
    {

        public Notificada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsNotificada()
        {
            return true;
        }

    }
}


//end Notificada