///////////////////////////////////////////////////////////
//  Plan.cs
//  Implementation of the Class Plan
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 18:32:20
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;

namespace RealizacionCU22.Modelo
{
    [Table("plan")]
    public class Plan : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public DateTime FechaCreacion { get; set; }
        public DateTime FechaFinResolucion { get; set; }
        public DateTime FechaInicioResolucion { get; set; }
        public virtual ICollection<Ticket> TrabajoARealizar { get; set; }

        public Plan()
        {

        }

        public void calcularCantidadTiempoResolucion()
        {

        }

        public void calcularCostoPorTarea()
        {

        }

        public void calcularCostoSolucion()
        {

        }

        public void calcularCostoTotalSolucion()
        {

        }

        public void conocerTicket()
        {

        }

        public void contarRecursoPlan()
        {

        }

        public void contarTickets()
        {

        }

        public void crearTicket()
        {

        }

        public void cuantificarRecurso()
        {

        }

        public void obtenerVigente()
        {

        }

        public void sosUltimo()
        {

        }

        public void sumarizarHorasDeTarea()
        {

        }

        public void sumarizarTotalHorasDeTarea()
        {

        }

    }
}
//end Plan