///////////////////////////////////////////////////////////
//  Proyecto.cs
//  Implementation of the Class Proyecto
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:37
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;

namespace RealizacionCU22.Modelo
{
    [Table("proyecto")]
    public class Proyecto : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public virtual Version Aplicacion { get; set; }
        public virtual Cliente Cliente { get; set; }
        public DateTime FechaAlta { get; set; }
        public string Nombre { get; set; }
        public string NombreClave { get; set; }
        public virtual ICollection<SolicitudMantenimiento> SolicitudesDeMantenimiento { get; set; }

        public Proyecto()
        {

        }

        public void BuscarSMEnProyecto()
        {

        }

        public int ContarSolicitudesPorPeriodo(DateTime inicioPeriodo, DateTime finPeriodo)
        {
            int contador = 0;
            foreach(SolicitudMantenimiento sm in SolicitudesDeMantenimiento)
            {
                if (sm.EsDePeriodo(inicioPeriodo, finPeriodo))
                {
                    contador++;
                }
            }
            return contador;
        }

        public void CrearSM()
        {

        }

        public void EsSMDeProyecto()
        {

        }

        /// 
        /// <param name="fechaActual"></param>
        public void RegistrarResolucionSM(DateTime fechaActual)
        {

        }

        public void SoyProyectoSegunFiltros()
        {

        }

        public void VerificarEstadoDeSM()
        {

        }

    }
}
//end Proyecto