///////////////////////////////////////////////////////////
//  Reclamada.cs
//  Implementation of the Class Reclamada
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:40
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Reclamada : EstadoSM
    {

        public Reclamada()
        {
            this.Nombre = this.GetType().ToString();
        }

        public new bool EsReclamada()
        {
            return true;
        }

    }
}

//end Reclamada