///////////////////////////////////////////////////////////
//  Resuelta.cs
//  Implementation of the Class Resuelta
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 17:17:44
//  Original author: camia
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    
    public class Resuelta : EstadoSM
    {

        public Resuelta()
        {
            this.Nombre = "Resuelta";
        }
        public new bool EsResuelta()
        {

            return true;
        }

    }
}

//end Resuelta