///////////////////////////////////////////////////////////
//  Rol.cs
//  Implementation of the Class Rol
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 19:55:14
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("rol")]
    public class Rol : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }

        public Rol()
        {

        }

        ~Rol()
        {

        }

        public virtual void Dispose()
        {

        }

        public void crear()
        {

        }

        public void esRol()
        {

        }

        public void getNombre()
        {

        }

        public void mostrarNombre()
        {

        }

        public void mostrarRol()
        {

        }

        public void setNombre()
        {

        }

    }
}
//end Rol