///////////////////////////////////////////////////////////
//  Solicitante.cs
//  Implementation of the Class Solicitante
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 18:32:49
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace RealizacionCU22.Modelo
{

    [Table("solicitante")]
    public class Solicitante : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Apellido { get; set; }
        public string AreaOGerencia { get; set; }
        public string CorreoElectronicoInstitucional { get; set; }
        public string CorreoElectronicoPersonal { get; set; }
        public string Direccion { get; set; }
        public string Nombre { get; set; }
        public string NumeroDoc { get; set; }
        public string RolEnArea { get; set; }
        public string TelefonoContacto { get; set; }
        
	    public virtual ICollection<Proyecto> Proyectos { get; set; }

        public virtual Usuario Usuario { get; set; }
        public virtual TipoDocumento TipoDoc { get; set; }

        public Solicitante()
        {

        }

    }
}
//end Solicitante