///////////////////////////////////////////////////////////
//  Tarea.cs
//  Implementation of the Class Tarea
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 19:55:26
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("tarea")]
    public class Tarea : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
        public double ValorPorHora { get; set; }

        public virtual Rol RolEjecutor { get; set; }

        public Tarea()
        {

        }

        ~Tarea()
        {

        }

        public virtual void Dispose()
        {

        }

        public void conocerRol()
        {

        }

        public void crear()
        {

        }

        public void esTarea()
        {

        }

        public void esTuRol()
        {

        }

        public void mostrarNombre()
        {

        }

        public void mostrarTarea()
        {

        }

        public void nuevoValorHora()
        {

        }

    }
}
//end Tarea