///////////////////////////////////////////////////////////
//  Ticket.cs
//  Implementation of the Class Ticket
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 18:48:32
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.IO;
using System;

namespace RealizacionCU22.Modelo
{
    [Table("ticket")]
    public class Ticket : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string DetalleTicket { get; set; }
        public DateTime FechaFinPrevista { get; set; }
        public DateTime FechaInicioPrevista { get; set; }
        public DateTime FechaInicioReal { get; set; }
        public double HorasEstimadas { get; set; }
        public string InformacionAnalisis { get; set; }
        public double ValorHoraReal { get; set; }

        public virtual ICollection<HistorialEstadoTicket> HistorialEstados { get; set; }
        public virtual MiembroEquipo MiembroEquipo { get; set; }
        public virtual Tarea Tarea { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }
        [NotMapped]
        public virtual ICollection<Archivo> Archivos { get; set; }

        public Ticket()
        {

        }

        public void agregarComentario()
        {

        }

        public void anular()
        {

        }

        public void calcularCostoTicket()
        {

        }

        public double calcularHorasConsumidas()
        {
            Random randD= new Random();
            Random randI = new Random();
            return randD.NextDouble() * randI.Next(100,500);
        }

        public void cambiarAsignacion()
        {

        }

        public void cerrar()
        {

        }

        public void conocerComentario()
        {

        }

        public void conocerHistorialEstadoTicket()
        {

        }

        public void conocerMiembroEquipo()
        {

        }

        public void conocerTarea()
        {

        }

        public void crear()
        {

        }

        public void enEjecucion()
        {

        }

        public void esCerrado()
        {

        }

        public void esDeRol()
        {

        }

        public void esDeTarea()
        {

        }

        public void estaSinResolver()
        {

        }

        public void finalizar()
        {

        }

        public void finalizarResolucion()
        {

        }

        public void iniciarResolucion()
        {

        }

        public void mostrarCostoYHorasConsumidas()
        {

        }

        public void mostrarDatosMiembroAsignado()
        {

        }

        public void mostrarDetalle()
        {

        }

        public void mostrarFechaFinReal()
        {

        }

        public void mostrarFechaHoraFinResolucion()
        {

        }

        public void mostrarFechaInicioReal()
        {

        }

        public void mostrarFechaInicioYFinPrevista()
        {

        }

        public void mostrarHorasConsumidas()
        {

        }

        public void mostrarHorasEstimadas()
        {

        }

        public void mostrarID()
        {

        }

        public void mostrarInformacionAnalisis()
        {

        }

        public void mostrarNombreTarea()
        {

        }

        public void obtenerTicket()
        {

        }

        public void obtenerUltimoResuelto()
        {

        }

        public void obtenerValorHorasReal()
        {

        }

        public void reabrir()
        {

        }

        public void sumarizarHorasConsumidas()
        {

        }

    }
}
//end Ticket