///////////////////////////////////////////////////////////
//  TipoSM.cs
//  Implementation of the Class TipoSM
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 18:32:13
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RealizacionCU22.Modelo
{
    [Table("tipo_solicitud")]
    public class TipoSM : IObjetoPersistente
    {
        [Key]
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }

        public TipoSM(string nombre, string desc)
        {
            this.Nombre = nombre;
            this.Descripcion = desc;
        }
        public TipoSM() { }
    }
}
//end TipoSM