///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      13-Nov-2019 19:55:34
//  Original author: Lucas
///////////////////////////////////////////////////////////
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace RealizacionCU22.Modelo
{
    [Table("usuario")]
    public class Usuario : IObjetoPersistente
    {

        [Key]
        public int Id { get; set; }
        public string NombreUsuario { get; set; }
        public string Password { get; set; }

        public Usuario()
        {

        }

        ~Usuario()
        {

        }

        public virtual void Dispose()
        {

        }

        public void cambiarPassword()
        {

        }

        public void crear()
        {

        }

        public void mostrarNombreUsuario()
        {

        }

        public void mostrarUsuario()
        {

        }

        public void obtenerCorreoElectrónicoInstitucionalUsuarioSolicitante()
        {

        }

        public void obtenerJP()
        {

        }

        public void obtenerNombreYApellidoJefe()
        {

        }

        public void obtenerUsuario()
        {

        }

        public void validarPassword()
        {

        }

    }
}
//end Usuario